name: Bygg pull request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          echo "Verifying"
          mvn verify -e --batch-mode --settings .github/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
