name: Publiser release
on:
  release:
    types: [ published ]

jobs:
  release:
    name: Kontrakt
    permissions:
      packages: write
    uses: navikt/fp-gha-workflows/.github/workflows/release-feature.yml@main
    with:
      release-version: ${{ github.event.release.tag_name }}
      release-profiles: ''
    secrets: inherit

  release-ee9:
    name: Kontrakt EE9
    permissions:
      packages: write
    uses: navikt/fp-gha-workflows/.github/workflows/release-feature.yml@main
    with:
      release-version: ${{ format('{0}-{1}', github.event.release.tag_name, 'jakarta') }}
      release-file: '-f ./ee9/pom.xml'
      release-profiles: ''
    secrets: inherit
