name: Publiser release
on:
  release:
    types: [ published ]

jobs:
  release:
    name: Kontrakt
    permissions:
      packages: write
    uses: navikt/fp-gha-workflows/.github/workflows/release-feature.yml@main
    with:
      release-version: ${{ github.event.release.tag_name }}
      release-profiles: ''
    secrets: inherit

  release-ee9:
    name: Kontrakt EE9
    needs: release
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Setup java and maven
        uses: navikt/fp-gha-workflows/.github/actions/setup-java-and-maven@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          java-version: '17'

      - name: Publish artifacts
        run: |
          mvn -B -s settings.xml versions:set -DnewVersion=${{ github.event.release.tag_name && '-jakarta' }} -f ./ee9/pom.xml
          mvn -B -s settings.xml -DskipTests clean deploy -f ./ee9/pom.xml
